// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PersonalWebsite.Controllers
{
    public partial class BlogController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BlogController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BlogController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult SinglePost()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SinglePost);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BlogController Actions { get { return MVC.Blog; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Blog";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Blog";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Read = "Read";
            public readonly string Tagged = "Tagged";
            public readonly string Manage = "Manage";
            public readonly string New = "New";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string SinglePost = "SinglePost";
            public readonly string RecentPosts = "RecentPosts";
            public readonly string RecentPostsList = "RecentPostsList";
            public readonly string PopularPostsList = "PopularPostsList";
            public readonly string Sidebar = "Sidebar";
            public readonly string PostArchive = "PostArchive";
            public readonly string TagCloud = "TagCloud";
            public readonly string SearchBar = "SearchBar";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Read = "Read";
            public const string Tagged = "Tagged";
            public const string Manage = "Manage";
            public const string New = "New";
            public const string Edit = "Edit";
            public const string Delete = "Delete";
            public const string SinglePost = "SinglePost";
            public const string RecentPosts = "RecentPosts";
            public const string RecentPostsList = "RecentPostsList";
            public const string PopularPostsList = "PopularPostsList";
            public const string Sidebar = "Sidebar";
            public const string PostArchive = "PostArchive";
            public const string TagCloud = "TagCloud";
            public const string SearchBar = "SearchBar";
        }


        static readonly ActionParamsClass_Read s_params_Read = new ActionParamsClass_Read();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Read ReadParams { get { return s_params_Read; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Read
        {
            public readonly string id = "id";
            public readonly string slug = "slug";
        }
        static readonly ActionParamsClass_Tagged s_params_Tagged = new ActionParamsClass_Tagged();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Tagged TaggedParams { get { return s_params_Tagged; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Tagged
        {
            public readonly string id = "id";
            public readonly string slug = "slug";
        }
        static readonly ActionParamsClass_New s_params_New = new ActionParamsClass_New();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_New NewParams { get { return s_params_New; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_New
        {
            public readonly string model = "model";
            public readonly string formCollection = "formCollection";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string model = "model";
            public readonly string formCollection = "formCollection";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string formCollection = "formCollection";
        }
        static readonly ActionParamsClass_SinglePost s_params_SinglePost = new ActionParamsClass_SinglePost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SinglePost SinglePostParams { get { return s_params_SinglePost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SinglePost
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
                public readonly string Manage = "Manage";
                public readonly string New = "New";
                public readonly string PopularPostsList = "PopularPostsList";
                public readonly string PostArchive = "PostArchive";
                public readonly string Read = "Read";
                public readonly string RecentPosts = "RecentPosts";
                public readonly string RecentPostsList = "RecentPostsList";
                public readonly string SearchBar = "SearchBar";
                public readonly string SideBar = "SideBar";
                public readonly string SinglePost = "SinglePost";
                public readonly string TagCloud = "TagCloud";
                public readonly string Tagged = "Tagged";
            }
            public readonly string Edit = "~/Views/Blog/Edit.cshtml";
            public readonly string Index = "~/Views/Blog/Index.cshtml";
            public readonly string Manage = "~/Views/Blog/Manage.cshtml";
            public readonly string New = "~/Views/Blog/New.cshtml";
            public readonly string PopularPostsList = "~/Views/Blog/PopularPostsList.cshtml";
            public readonly string PostArchive = "~/Views/Blog/PostArchive.cshtml";
            public readonly string Read = "~/Views/Blog/Read.cshtml";
            public readonly string RecentPosts = "~/Views/Blog/RecentPosts.cshtml";
            public readonly string RecentPostsList = "~/Views/Blog/RecentPostsList.cshtml";
            public readonly string SearchBar = "~/Views/Blog/SearchBar.cshtml";
            public readonly string SideBar = "~/Views/Blog/SideBar.cshtml";
            public readonly string SinglePost = "~/Views/Blog/SinglePost.cshtml";
            public readonly string TagCloud = "~/Views/Blog/TagCloud.cshtml";
            public readonly string Tagged = "~/Views/Blog/Tagged.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_BlogController : PersonalWebsite.Controllers.BlogController
    {
        public T4MVC_BlogController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ReadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string slug);

        public override System.Web.Mvc.ActionResult Read(int id, string slug)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Read);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "slug", slug);
            ReadOverride(callInfo, id, slug);
            return callInfo;
        }

        partial void TaggedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string slug);

        public override System.Web.Mvc.ActionResult Tagged(int id, string slug)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Tagged);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "slug", slug);
            TaggedOverride(callInfo, id, slug);
            return callInfo;
        }

        partial void ManageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Manage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage);
            ManageOverride(callInfo);
            return callInfo;
        }

        partial void NewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult New()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.New);
            NewOverride(callInfo);
            return callInfo;
        }

        partial void NewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PersonalWebsite.Models.Blog.NewViewModel model, System.Web.Mvc.FormCollection formCollection);

        public override System.Web.Mvc.ActionResult New(PersonalWebsite.Models.Blog.NewViewModel model, System.Web.Mvc.FormCollection formCollection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.New);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formCollection", formCollection);
            NewOverride(callInfo, model, formCollection);
            return callInfo;
        }

        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PersonalWebsite.Models.Blog.EditViewModel model, System.Web.Mvc.FormCollection formCollection);

        public override System.Web.Mvc.ActionResult Edit(PersonalWebsite.Models.Blog.EditViewModel model, System.Web.Mvc.FormCollection formCollection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formCollection", formCollection);
            EditOverride(callInfo, model, formCollection);
            return callInfo;
        }

        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection formCollection);

        public override System.Web.Mvc.ActionResult Delete(System.Web.Mvc.FormCollection formCollection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formCollection", formCollection);
            DeleteOverride(callInfo, formCollection);
            return callInfo;
        }

        partial void SinglePostOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, PersonalWebsite.Models.Blog.SinglePostViewModel model);

        public override System.Web.Mvc.PartialViewResult SinglePost(PersonalWebsite.Models.Blog.SinglePostViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SinglePost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SinglePostOverride(callInfo, model);
            return callInfo;
        }

        partial void RecentPostsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult RecentPosts()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.RecentPosts);
            RecentPostsOverride(callInfo);
            return callInfo;
        }

        partial void RecentPostsListOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult RecentPostsList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.RecentPostsList);
            RecentPostsListOverride(callInfo);
            return callInfo;
        }

        partial void PopularPostsListOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult PopularPostsList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.PopularPostsList);
            PopularPostsListOverride(callInfo);
            return callInfo;
        }

        partial void SidebarOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult Sidebar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Sidebar);
            SidebarOverride(callInfo);
            return callInfo;
        }

        partial void PostArchiveOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult PostArchive()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.PostArchive);
            PostArchiveOverride(callInfo);
            return callInfo;
        }

        partial void TagCloudOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult TagCloud()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.TagCloud);
            TagCloudOverride(callInfo);
            return callInfo;
        }

        partial void SearchBarOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult SearchBar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SearchBar);
            SearchBarOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
